# Values for the calculator

from datetime import timedelta

MINIMUM_CART_VALUE = 1000
BASE_DELIVERY_FEE = 200
ADDITIONAL_DISTANCE_FEE = 100
ADDITIONAL_DISTANCE_THRESHOLD = 500
ITEM_SURCHARGE = 50
BULK_FEE_THRESHOLD = 12
BULK_FEE = 120
MAX_DELIVERY_FEE = 1500
CART_VALUE_THRESHOLD = 20000
RUSH_START_TIME = timedelta(hours=15)
RUSH_END_TIME = timedelta(hours=19)